Task/Models/ErrorViewModel.cs
namespace Task.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Task/Models/LecturerModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Task.Models
{
    public class LecturerModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Email { get; set; }
        public int Phone { get; set; }

    }
}

Task/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Task.Models;

namespace Task.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Task/Controllers/LecturerController.cs
using Microsoft.AspNetCore.Mvc;

namespace IS_Task.Controllers
{
    public class LecturerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Task/Controllers/LecturersController.cs
using IS_Task.Data;
using Microsoft.AspNetCore.Mvc;
using Task.Models;

namespace IS_Task.Controllers
{
    public class LecturersController : Controller
    {
        private readonly ApplicationDbContext _db;
        public LecturersController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List <LecturerModel> objLecturersList  = _db.Lecturers.ToList();
            return View(objLecturersList);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(LecturerModel obj)
        {
           if(ModelState.IsValid) { 
            _db.Lecturers.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            LecturerModel lecturersFromDb = _db.Lecturers.Find(id);
            if (lecturersFromDb == null)
            {
                return NotFound();
            }
            return View(lecturersFromDb);
        }
        [HttpPost]
        public IActionResult Edit(LecturerModel obj)
        {
            if (ModelState.IsValid)
            {
                _db.Lecturers.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Task/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Task/Views/Lecturers/Create.cshtml
@model LecturerModel

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add new</h2>
            <hr/>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for=Name class="p-0"></label>
            <input asp-for=Name type="text" class="form-control"/>
        </div>
         <div class="mb-3 row">
             <label asp-for=Email class="p-0"></label>
             <input asp-for=Email type="text" class="form-control"/>
         </div>
        <div class="mb-3 row">
            <label asp-for=Phone class="p-0"></label>
            <input asp-for=Phone type="text" class="form-control" />
        </div>

         <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control" style="width:150px">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Lecturers" asp-action="Index" class="btn btn-outline-secondary form-control" style="width:150px">Back to list</a>
            </div>
     </div>
     </div>
</form>   

Task/Views/Lecturers/Index.cshtml
@model List<LecturerModel>

<div class="container">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text primary">Lecturers list</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Lecturers" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-square"></i> Add new lectutrer
            </a>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>
                Lecturer Name
            </th>
            <th>
                Lecturer e-mail
            </th>
        </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model.OrderBy(u => u.Name))
            {
                <tr>
                    <td> @obj.Name </td>
                    <td> @obj.Email </td>
                    <td>
                        <div class="w-75 btnbtn-group" role="group">
                            <a asp-controller="Category" asp-action="Edit" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i>Edit
                            </a>
                            <a asp-controller="Category" asp-action="Delete" class="btn btn-delete mx-2">
                                <i class="bi bi-trash-fill"></i>Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Task/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Task.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Lecturers" asp-action="Index">Lecturers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Task - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>